---
- name: Install deb822 dependency
  ansible.builtin.apt:
    pkg: python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add New Relic repo
  ansible.builtin.deb822_repository:
    name: newrelic
    types: [deb]
    uris: https://apt.newrelic.com/debian/
    suites: newrelic
    components: non-free
    signed_by: /etc/apt/keyrings/newrelic-repo.gpg

- name: Find legacy New Relic list file
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.list"
    contains: 'apt\.newrelic\.com'
  register: new_relic_legacy_list

- name: Remove legacy New Relic list file
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ new_relic_legacy_list.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Install New Relic
  ansible.builtin.apt:
    pkg: newrelic-php5
    state: present
    update_cache: true
    cache_valid_time: 3600
  notify: Restart php-fpm

- name: Apply settings
  ansible.builtin.template:
    src: "newrelic.ini.j2"
    dest: "/etc/php/{{ php_version }}/mods-available/newrelic.ini"
    owner: root
    group: root
    mode: "0644"
  notify: Restart php-fpm
