---
- name: Install deb822 dependency
  ansible.builtin.apt:
    pkg: python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add Redis repository
  ansible.builtin.deb822_repository:
    name: redis
    types: [deb]
    uris: https://packages.redis.io/deb
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /etc/apt/keyrings/redis-archive-keyring.gpg
  register: redis_repo

- name: Update apt cache after adding repository # noqa: no-handler
  ansible.builtin.apt:
    update_cache: true
  when: redis_repo is changed

- name: Pin Redis version
  ansible.builtin.template:
    src: redis.pref.j2
    dest: /etc/apt/preferences.d/redis.pref
    owner: root
    group: root
    mode: "0644"
  when: redis_version | length > 0

- name: Remove Redis version pin
  ansible.builtin.file:
    path: /etc/apt/preferences.d/redis.pref
    state: absent
  when: redis_version | length == 0

- name: Install Redis
  ansible.builtin.apt:
    pkg: redis-server
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Configure Redis
  ansible.builtin.template:
    src: redis-ansible.conf.j2
    dest: /etc/redis/redis-ansible.conf
    owner: root
    group: redis
    mode: "0640"
  notify: Restart redis

- name: Include Redis overrides
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    line: include /etc/redis/redis-ansible.conf
    insertafter: EOF
    state: present
  notify: Restart redis

- name: Enable and start Redis
  ansible.builtin.systemd:
    name: redis-server
    enabled: true
    state: started

- name: Add vm.overcommit_memory = 1 to sysctl
  ansible.posix.sysctl:
    name: vm.overcommit_memory
    value: 1
    reload: true
  when: redis_overcommit_memory
