---
# - { name: example, host: 127.0.0.1, password: secret, priv: *.*:USAGE }
mysql_users: []
# - { name: example, collation: utf8_general_ci, encoding: utf8 }
mysql_databases: []
mysql_innodb_redo_log_capacity: 256M
mysql_innodb_flush_log_at_trx_commit: 1
mysql_slow_query_log: 0
mysql_login_unix_socket: /var/run/mysqld/mysqld.sock

mysql_version: 8.4-lts
