---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    mysql_innodb_buffer_pool_size: 128M
    mysql_databases:
      - name: molecule_db
    mysql_users:
      - name: molecule_user
        host: "%"
        password: "{{ mysql_molecule_user_password }}"
        salt: "{{ mysql_molecule_user_salt }}"
        priv: "molecule_db.*:ALL"
  roles:
    - role: tborealis.roles.mysql
