namespace: tborealis
name: roles
version: 1.0.0
readme: README.md
authors:
  - Tom Borealis <tom@lampbristol.com>
description: A collection of roles for provisioning local and production environments
license_file: 'LICENSE.txt'
repository: https://github.com/tborealis/ansible-roles
tags:
  - infrastructure
  - linux
build_ignore:
  - .idea
  - .github
  - .gitignore
dependencies:
  ansible.posix: '*'
  community.general: '*'
  community.mysql: '*'
  community.postgresql: '*'
  community.rabbitmq: '*'
