---
collections:
  - name: ansible.posix
  - name: ansible.mysql
  - name: community.general
  - name: community.postgresql
  - name: community.rabbitmq
  - name: community.docker # dev/test only: used by the molecule docker driver
roles:
  - name: ecgalaxy.aws_cli
