---
- name: Install deb822 dependency
  ansible.builtin.apt:
    pkg: python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add PostgreSQL repository
  ansible.builtin.deb822_repository:
    name: postgresql
    types: [deb]
    uris: https://apt.postgresql.org/pub/repos/apt/
    suites: "{{ ansible_facts['distribution_release'] }}-pgdg"
    components: main
    signed_by: /etc/apt/keyrings/postgresql.gpg
    state: present
  register: pgsql_repo

- name: Find legacy PostgreSQL list file
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.list"
    contains: 'apt\.postgresql\.org'
    read_whole_file: true
  register: pgsql_legacy_list

- name: Remove legacy PostgreSQL list file
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ pgsql_legacy_list.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Update apt cache after adding repository # noqa: no-handler
  ansible.builtin.apt:
    update_cache: true
  when: pgsql_repo is changed

- name: Install PostgreSQL client packages
  ansible.builtin.apt:
    pkg: "{{ pgsql_client_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
