---
phpbu_enable: true

phpbu_version: "6.0.33"

phpbu_cron_enable: true
# Five cron fields (minute, hour, day, month, weekday); daily at 02:30.
phpbu_cron_time: ["30", "2", "*", "*", "*"]

phpbu_log_dir: /var/log/phpbu
phpbu_lib_dir: /var/lib/phpbu
phpbu_backup_dir: "{{ phpbu_lib_dir }}/backups"

# base64 encoded ed25519 private key, use `base64 -w0 <key file>`
phpbu_private_key:
