---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    node_version: "{{ node_molecule_version }}"
    node_version_manager: nvm
    node_nvm_config:
      - user: "{{ node_molecule_user }}"
        default_version: "{{ node_molecule_nvm_node_major }}"
        versions:
          - version: "{{ node_molecule_nvm_node_major }}"
            global_packages:
              - "{{ node_molecule_global_package }}"
  roles:
    - role: tborealis.roles.node
