---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    nvm_config:
      - user: "{{ nvm_molecule_user }}"
        default_version: "{{ nvm_molecule_node_major }}"
        versions:
          - version: "{{ nvm_molecule_node_major }}"
            corepack_enable: true
            global_packages:
              - "{{ nvm_molecule_global_package }}"
  roles:
    - role: tborealis.roles.nvm
