---
- name: Converge
  hosts: all

  vars:
    base_clean_hosts: false

  pre_tasks:
    - name: Update APT
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: lampbristol.lampsible.base
