---
driver:
  name: docker
platforms:
  - name: instance
    image: lampsible-testing:${MOLECULE_DISTRO:-debian12}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    override_command: false
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
#    - dependency
#    - cleanup
    - destroy
    - syntax
    - create
#    - prepare
    - converge
    - idempotence
#    - side_effect
#    - verify
#    - cleanup
    - destroy
