---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    nginx_client_max_body_size: 16m
    nginx_vhosts:
      - src: molecule.conf.j2
        dest: molecule.conf
        enabled: true
    nginx_basic_auth:
      - name: "{{ nginx_molecule_auth_user }}"
        password: "{{ nginx_molecule_auth_password }}"
        path: "{{ nginx_molecule_htpasswd_path }}"
  roles:
    - role: tborealis.roles.nginx
