---
- name: Create env files
  ansible.builtin.template:
    src: env_file.j2
    dest: "{{ item.file }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group | default(item.owner) }}"
    mode: "{{ item.mode | default('0644') }}"
  with_items: "{{ env_file_list }}"
  loop_control:
    label: "{{ item.file }}"
