---
- name: Find legacy Node list files
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.list"
    contains: 'deb\.nodesource\.com'
  register: node_legacy_list

- name: Remove legacy Node list files
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ node_legacy_list.files }}"
  loop_control:
    label: "{{ item.path }}"
