---
- name: "Find Node repo files: {{ version }}"
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns:
      - "*.list"
      - "*.sources"
    contains: 'deb\.nodesource\.com/node_{{ version }}\.x'
  register: node_remove_list

- name: "Remove Node repo: {{ version }}"
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ node_remove_list.files }}"
  loop_control:
    label: "{{ item.path }}"
