---
- name: Converge
  hosts: all
  become: true
  vars_files:
    - vars.yml
  vars:
    node_version: "{{ node_molecule_version }}"
    node_yarn_enabled: true
    node_yarn_version: "{{ node_molecule_yarn_version }}"
    node_pnpm_enabled: true
    node_pnpm_version: "{{ node_molecule_pnpm_version }}"
    node_global_packages:
      - "{{ node_molecule_global_package }}"
    node_npmrc:
      - template: npmrc.j2
        dir: /root
        user: root
  roles:
    - role: tborealis.roles.node
