---
- name: Check the installed Session Manager plugin version
  ansible.builtin.command: session-manager-plugin --version
  register: aws_cli_ssm_installed
  failed_when: false
  changed_when: false

- name: Install the Session Manager plugin
  when: aws_cli_ssm_installed.rc != 0 or aws_cli_ssm_installed.stdout != aws_cli_ssm_version
  block:
    - name: Download the Session Manager plugin
      ansible.builtin.get_url:
        url: "https://s3.amazonaws.com/session-manager-downloads/plugin/{{ aws_cli_ssm_version }}/{{ aws_cli_ssm_architecture_map[ansible_facts['architecture']] }}/session-manager-plugin.deb"
        dest: "{{ aws_cli_download_path }}/session-manager-plugin.deb"
        checksum: "{{ aws_cli_ssm_checksums[aws_cli_ssm_architecture_map[ansible_facts['architecture']]] }}"
        mode: "0644"

    - name: Install the Session Manager plugin package
      ansible.builtin.apt:
        deb: "{{ aws_cli_download_path }}/session-manager-plugin.deb"
        state: present

    - name: Clean up the plugin download
      ansible.builtin.file:
        path: "{{ aws_cli_download_path }}/session-manager-plugin.deb"
        state: absent
