---
- name: Install Composer prerequisites
  ansible.builtin.apt:
    pkg:
      - "php{{ php_version }}-zip"
      - curl
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install Composer
  ansible.builtin.shell: set -o pipefail && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
  args:
    executable: /bin/bash
    creates: /usr/local/bin/composer
  register: php_composer_install

- name: Update Composer to latest version
  ansible.builtin.command: composer self-update
  register: php_composer_update
  changed_when: "'Updating to version' in php_composer_update.stdout"
  when: php_composer_keep_updated

- name: Create bash completion directory
  ansible.builtin.file:
    path: /etc/bash_completion.d
    state: directory
    mode: "0755"

- name: Check if Composer Bash completion exists
  ansible.builtin.stat:
    path: /etc/bash_completion.d/composer
  register: php_composer_completion_stat

- name: Generate Composer Bash completion
  ansible.builtin.shell: "COMPOSER_ALLOW_SUPERUSER=1 composer completion bash > /etc/bash_completion.d/composer"
  changed_when: true
  when: php_composer_install is changed or php_composer_update is changed or not php_composer_completion_stat.stat.exists

- name: Install Composer global packages
  community.general.composer:
    command: require
    global_command: true
    arguments: "{{ item.name }}={{ item.version }}"
    prefer_dist: true
  loop: "{{ php_composer_global_packages }}"
  loop_control:
    label: "{{ item.name }}"
