---
- name: Install deb822 dependency
  ansible.builtin.apt:
    pkg: python3-debian
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add PHP repository
  ansible.builtin.deb822_repository:
    name: php-sury
    types: [deb]
    uris: https://packages.sury.org/php/
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: /etc/apt/keyrings/php-sury-repo.gpg
  register: php_sury_repo

- name: Find legacy PHP list file
  ansible.builtin.find:
    paths: /etc/apt/sources.list.d
    patterns: "*.list"
    contains: 'packages\.sury\.org'
    read_whole_file: true
  register: php_sury_legacy_list

- name: Remove legacy PHP list file
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ php_sury_legacy_list.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Update apt cache after adding repository # noqa: no-handler
  ansible.builtin.apt:
    update_cache: true
  when: php_sury_repo is changed
